# NUMPY FOR DATASCIENCE

**NumPy arrays** are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [1]:
import numpy as np
x=np.array([1,2,3])
print(x)

[1 2 3]


Numpy also access the zeros matrix as well as the ones matrix in order to get we have the for zero [np.zeros(no od zeros )] and for the ones we can write [np.ones(no_of_1 want)]

In [2]:
import numpy as np
x=np.zeros(2)
print(x)
y=np.ones(3)
print(y)

[0. 0.]
[1. 1. 1.]


**Empty array** :This function creates the array whose initial state is random which is based on the state of memory .The reason is to use it for the speed just after the element stores in it.

In [3]:
import numpy as np
emp=np.zeros(3)
ep=np.empty(2)
print(emp)
print(ep)

[0. 0. 0.]
[0. 0.]


**np.arange()**  : -It is a function which is used as a range function and print the all value between the name in an numpy array
np.arange(start,end,step) :It provided the good feature to store values inside the array .

In [4]:
import numpy as np
x=np.arange(7)
print(x)
y=np.arange(0,22,2)
print(y)

[0 1 2 3 4 5 6]
[ 0  2  4  6  8 10 12 14 16 18 20]


**linepsace()** :  It is used to the space inside our array.

In [5]:
import numpy as np
x=np.linspace(0,10,num=10)
print(x
)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


**np.ones()**: It  print the 0 according to the need and given the dtype as INT64 as basis of the data to removing the floating point.

In [6]:
import numpy as np
z=np.ones(5,dtype=np.float64)
print(z)
c=np.ones(2,dtype=np.int64)
print(c)


[1. 1. 1. 1. 1.]
[1 1]


Adding,removing and sorting elements :
This is brings the sorting technique to found the element of the array .
**np.sort()** : Sort the element of the array
**np.concatenate()** : Adding the two numpy array 


In [7]:
#sorting example
import numpy as np
ar=np.array([1,2,3,4,8,6,5])
print(ar)
ar=np.sort(ar)
print("sorting array",ar)

[1 2 3 4 8 6 5]
sorting array [1 2 3 4 5 6 8]


In [8]:
#concatenate example
import numpy as np
a=np.array([1,3,5,6,7])
b=np.array([3,4,6,7,8,9,0])
newar=np.concatenate((a,b))
print("after concatenation : ",newar)
print("after sorting  : ",np.sort(newar))

after concatenation :  [1 3 5 6 7 3 4 6 7 8 9 0]
after sorting  :  [0 1 3 3 4 5 6 6 7 7 8 9]


Concatenation with new axis  in order to remove elements from an array, it’s simple to use indexing to select the elements that you want to keep.
example below  


In [9]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
arr=np.concatenate((x,y),axis=0)
print("with down wise",arr)


with down wise [ 1  2  3  4  5  6  7  8  9 10]


How to know the shape and size of the array:
function : ndarray.ndim --will tell you the number of axes, or dimensions, of the array.
        ndarray.size --will tell you the total number of elements of the array. This is the product of the elements of the array’s    shape.
        ndarray.shape -- will display a tuple of integers that indicate the number of elements stored along each dimension of the array. 
If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).
lets check the example of each

In [10]:
import numpy as np
array=np.array([
[[1,2,3,4],
[5,6,7,8]],
[[8,6,4,3],
[4,5,6,7]],
[[2,3,4,5],
[6,7,8,9]],
])

print("the array no of dimension",array.ndim)
print("the array size : ",array.size)
print("the shape of the array : ",array.shape)




the array no of dimension 3
the array size :  24
the shape of the array :  (3, 2, 4)


Reshape of an array :
using arr.reshape() will give a new shape to a array without changing the data .  

In [11]:
import numpy as np
a=np.arange(6)
print(a)
b=a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [12]:
import numpy as n
m=n.arange(2,22,2)
print("the arange data is : ",m)
print("for reshaping it as : ")
nn=m.reshape(5,2)
print(nn)

the arange data is :  [ 2  4  6  8 10 12 14 16 18 20]
for reshaping it as : 
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


INDEXING AND SLICING :
we can easily do the indexing and slicing like as we can do in python list 


In [13]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8])
print("slicing have been starting from there :")
b=ar.reshape(1,8)
print("shaping is : ",b)
print(ar[0])
print(ar[5])
print(ar[6])
print("slicing is from there : ")
print(ar[:9])
print(ar[::])
print(ar[-1:])
print(ar[:-1])


slicing have been starting from there :
shaping is :  [[1 2 3 4 5 6 7 8]]
1
6
7
slicing is from there : 
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[8]
[1 2 3 4 5 6 7]


WE can do the same thing with 2D array
let check the example

In [14]:
import numpy as m
arry=m.array([[1,2,3,4],
[4,5,6,7],
[7,6,5,5],
[4,7,5,3]])
print(arry)
print("indexing is from there : ")
print(arry[0])
print(arry[1])
print(arry[2])
print(arry[3])
print("slicing starts from there")
print(arry[1:])
print(arry[:-1])
print("slicing of arry[0:4:1]",arry[1:4:2])
print("slicing of arr[::-1]",arry[::-1])

[[1 2 3 4]
 [4 5 6 7]
 [7 6 5 5]
 [4 7 5 3]]
indexing is from there : 
[1 2 3 4]
[4 5 6 7]
[7 6 5 5]
[4 7 5 3]
slicing starts from there
[[4 5 6 7]
 [7 6 5 5]
 [4 7 5 3]]
[[1 2 3 4]
 [4 5 6 7]
 [7 6 5 5]]
slicing of arry[0:4:1] [[4 5 6 7]
 [4 7 5 3]]
slicing of arr[::-1] [[4 7 5 3]
 [7 6 5 5]
 [4 5 6 7]
 [1 2 3 4]]


Some conditions will be given to that array then find result

In [15]:
import numpy as nn
m=nn.array([
    [1,2,3,4],
    [9,8,7,6],
    [4,5,7,8],
    [7,8,9,9]
])
print("the array is : ",m)

the array is :  [[1 2 3 4]
 [9 8 7 6]
 [4 5 7 8]
 [7 8 9 9]]


In [16]:
import numpy as np
d=np.array([1,2,3,4,5,6,7])
print(d[d>5])
print(d[d<0])
print(d>1)
print(d<0)
print(d[d>1])


[6 7]
[]
[False  True  True  True  True  True  True]
[False False False False False False False]
[2 3 4 5 6 7]


In [17]:
five=d[d>5]
print(five)
divisible=d[d%2==0]
print(divisible)
c=d[(d>=1) & (d<=5)]
print(c)

[6 7]
[2 4 6]
[1 2 3 4 5]


more practices for the 2D array

In [18]:
import numpy as np
s=np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
m=s.reshape(1,12)
print(s)
print(m)
nonzero=np.nonzero(s<5)
print("nonzero element in the array: ",nonzero)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]
[[ 1  2  3  4  5  6  7  8 11 12 13 14]]
nonzero element in the array:  (array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [19]:
import numpy as nx
b=nx.array([
[1,2,3],[4,5,6],[7,8,9],
])
k=nx.nonzero(b<5)
print(k)


(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))


Here we can created the list of coordinates for that array


In [20]:
import numpy as nn
aa=nn.array([
[1,2,3,4],[5,6,7,8],[9,10,11,12]
])
bb=nn.nonzero(aa<5)
print("the array are : ",bb)
print(aa[bb])
coordinate=list(zip(bb[0],bb[1]))
for c in coordinate:
    print(c)


the array are :  (array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))
[1 2 3 4]
(0, 0)
(0, 1)
(0, 2)
(0, 3)


How do we crate the array from the existing data
we can created it with the slicing and indexing

In [21]:
import numpy as nk
b=nk.array([1,2,3,4,5,6,7,8,9])
print(b[2:4])
print(b[3:8])

[3 4]
[4 5 6 7 8]


In [22]:
import numpy as n
a=n.array([1,2,3,4,5,6,7,8,9,0])
ar=a[3:8]
print(ar)

[4 5 6 7 8]


You can create a new array from a section of your array any time by specifying where you want to slice your array
You can stack them vertically with vstack Or stack them horizontally with hstack .

In [23]:
import numpy as np
a1=np.array([
    [1,2],[3,4]
])
a2=np.array([
    [5,6],[7,8]
])
m=np.vstack((a1,a2))
print("vertically stack : ",m)
y=np.hstack((a1,a2))
print("horizontal stack : ",y)

vertically stack :  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stack :  [[1 2 5 6]
 [3 4 7 8]]


You can split an array into several smaller arrays using hsplit. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur

In [24]:
import numpy as np
xx=np.arange(1,25).reshape(2,12)
print(xx)
yy=np.hsplit(xx,3)
print(yy)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


Using the copy method will make a complete copy of the array and its data (a deep copy). To use this on your array, you could run:

In [25]:
import numpy as m
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m1=m[0,:]
print(m1)
m2=m[0]
print(m2)
m3=m[1,3]
m[0,1]=22
print(m)
m[1,1]=15
print(m)

[1 2 3 4]
[1 2 3 4]
[[ 1 22  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1 22  3  4]
 [ 5 15  7  8]
 [ 9 10 11 12]]


Basic array operations
This section covers addition, subtraction, multiplication, division, and more .
Once you’ve created your arrays, you can start to work with them

In [26]:
#Start with addition
import numpy as nn
a=nn.array([1,2])
b=nn.ones(2,dtype=int)
print("Addition of a{} and b{} is ".format(a,b),a+b)
#subtraction here
c=nn.array([3,2])
d=nn.ones(2,dtype=int)
print("subtraction of {} and {} is : ".format(c,d),c-d)
#multiplication is here
e=nn.array([3,2])
f=nn.ones(2,dtype=int)
print("the multiplication of {} and {} is : ".format(e,f),e*f)
#division is here
m=nn.array([3,4])
n=nn.ones(2,dtype=int)
print("the division is {} and {} is".format(m,n),m/n)



Addition of a[1 2] and b[1 1] is  [2 3]
subtraction of [3 2] and [1 1] is :  [2 1]
the multiplication of [3 2] and [1 1] is :  [3 2]
the division is [3 4] and [1 1] is [3. 4.]


Do some more practise 


In [27]:
import numpy as num
a=num.array([3,2])
b=num.array([3,2])
print("the addition is {} and {} ".format(a,b),a+b)
print("The subtraction is {} and  {} ".format(a,b),a-b)
print("The multiplication is {} and  {} ".format(a,b),a*b)
print("The division  is {} and  {} ".format(a,b),a/b)

the addition is [3 2] and [3 2]  [6 4]
The subtraction is [3 2] and  [3 2]  [0 0]
The multiplication is [3 2] and  [3 2]  [9 4]
The division  is [3 2] and  [3 2]  [1. 1.]


Sum function is used to calculate the sum of all element of an array .


In [28]:
import numpy as n
a=n.array([1,2,3,4,5,6,7,8,9,10])
print("the sum of all element is  : ",a.sum())
#***********************other method*********************
s=0
for i in a:
    s=s+i
print("the sum is : ",s)

the sum of all element is  :  55
the sum is :  55


If u want to add the row and column in an 2D array then you should apply this

In [29]:
import numpy as n
a=n.array([[3,4],[4,5]])
print("Sum of the maxtrix element at row wise: ",a.sum(axis=0))
print("SUm of the matrix element at column wise : ",a.sum(axis=1))


Sum of the maxtrix element at row wise:  [7 9]
SUm of the matrix element at column wise :  [7 9]


In [30]:
z=n.array([1,2,3,4])
print(z*2)

[2 4 6 8]


For getting maximum and minimum element we use the min() and max() element.


In [31]:
import numpy as nn
s=nn.array([1,2,3,4,888])
print("maximum value in array is",s.max())
print("minimum value in array is",s.min())

maximum value in array is 888
minimum value in array is 1


Lets start with the floating values : 


In [32]:
import numpy as np
z=np.array([
    [1.222  , 2.222, 3.222],
    [4.222  ,8.555 ,9.888],
    [0.222  ,7.434 ,9.990],
])
print("minimum is ",z.min())
print("minimum with row wise: ",z.min(axis=0))
print("minimum with column wise: ",z.min(axis=1))
print("maximum is : ",z.max())
print("maximum with row wise: ",z.max(axis=0))
print("maximum with column wise is :",z.max(axis=1))
print("the sum is  : ",z.sum())

minimum is  0.222
minimum with row wise:  [0.222 2.222 3.222]
minimum with column wise:  [1.222 4.222 0.222]
maximum is :  9.99
maximum with row wise:  [4.222 8.555 9.99 ]
maximum with column wise is : [3.222 9.888 9.99 ]
the sum is  :  46.977


You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row. In this case, NumPy will use its broadcast rules for the operation.

In [33]:
import numpy as np
data=np.array([[1,2],[3,4],[5,6]])
one=np.array([[1,1]])
d=data+one
print("Sum of the data: ",d)

Sum of the data:  [[2 3]
 [4 5]
 [6 7]]


In [34]:
import numpy as np
dd=np.ones((4,2,2))
print(dd)


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


 NumPy offers functions like ones() and zeros(), and the random.Generator class for random number generation for that. All you need to do is pass in the number of elements you want it to generate:
 for genrating the random number simplest way is: rng = np.random.default_rng() 

In [35]:
import numpy as np
m=np.ones(4)
print(m)
z=np.zeros(4)
print("zeros ae  : ",z)
print("for random no : ")
rng=np.random.default_rng()
mm=rng.random(4)
print("random is",mm)
rmg=np.random.random(5)
print("rmg",rmg)

[1. 1. 1. 1.]
zeros ae  :  [0. 0. 0. 0.]
for random no : 
random is [0.30879235 0.7462771  0.15358467 0.66732087]
rmg [0.60546438 0.64790488 0.79062749 0.85533081 0.71667803]


Creation of 2D array with using ones ,zeros and random


In [36]:
import numpy as np
a=np.ones((3,2))
print("the 2d array is:\n" ,a)
b=np.zeros((3,4))
print("the zeros are : \n",b)
rng=np.random.default_rng()
r=rng.random((3,2))
print("random no is: \n",r)

the 2d array is:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
the zeros are : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
random no is: 
 [[0.59585245 0.67100788]
 [0.34150225 0.17224109]
 [0.05323051 0.38053308]]


Generating random number or integer: while in the last program we have noticed that  random values of the array is . FLOAT value but if we want to know how to change many ones said that we can also do like dtype=int but it not probably work with the random lets do one example to check.
low=0 for minimum value and high=maximum value.

In [37]:
import numpy as np
rng=np.random.default_rng()
c=rng.integers(low=0,high=10,size=(2,6)) #rng.integers(5,size=(2,4))
print("c is random values is \n",c)

c is random values is 
 [[9 6 5 2 0 8]
 [1 9 9 5 5 1]]


Unique value  and its count (same as list ,tuple,string)
Unique values are the values which have only one existence and for searching multiple values in many values.
for getting the index value  and occurence_counting we have been used as . 


In [38]:
import numpy as n
a=n.array([1,2,3,4,5,6,7,8,1,2,3,55,6,7,8,90,10,22,31,1,4,5,2,])
print("the array is : ",a)
u=np.unique(a)
print("unique values are : ",u)
unique_value,indices_list=np.unique(a,return_index=True)
print("unique values are \n",unique_value,"\nunique values are index of\n",indices_list)

the array is :  [ 1  2  3  4  5  6  7  8  1  2  3 55  6  7  8 90 10 22 31  1  4  5  2]
unique values are :  [ 1  2  3  4  5  6  7  8 10 22 31 55 90]
unique values are 
 [ 1  2  3  4  5  6  7  8 10 22 31 55 90] 
unique values are index of
 [ 0  1  2  3  4  5  6  7 16 17 18 11 15]


In [39]:
import numpy as np
a=np.array([1,2,11,3,4,5,6,33,4,6,43,1,21,2,2,1,3,5,2,45])
print("array is : ",a)
unique=np.unique(a)
print("unique value is : ",unique)
print("the indexes of the array is: ")
unique,indices_list=np.unique(a,return_index=True)
print("unqie value is",unique_value)
print("index of the unique list is: ",indices_list)
print("repeated values are counted as : ")
unique_value,occurence_count=np.unique(a, return_counts=True)
print("occurence of the unique values is  : ",occurence_count)

array is :  [ 1  2 11  3  4  5  6 33  4  6 43  1 21  2  2  1  3  5  2 45]
unique value is :  [ 1  2  3  4  5  6 11 21 33 43 45]
the indexes of the array is: 
unqie value is [ 1  2  3  4  5  6  7  8 10 22 31 55 90]
index of the unique list is:  [ 0  1  3  4  5  6  2 12  7 10 19]
repeated values are counted as : 
occurence of the unique values is  :  [3 4 2 2 2 2 1 1 1 1 1]


This would be also help with the 2D array as like the above example.

In [40]:
import numpy as nn
array_2=nn.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4],[1,2,5,9]])
print("2 dimension array is: \n",array_2)
print("find the unique values : ")
unique_value=nn.unique(array_2)
print("unique value is : ",unique_value)
print("for getting the index we should used: ")
unique_value,indices_list=nn.unique(array_2,return_index=True)
print("indexices is: ",indices_list)
print("counts the repeated values: ")
unique_value,occurence_count=nn.unique(a,return_counts=True)
print("occurence_count \n",occurence_count)

2 dimension array is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 1  2  5  9]]
find the unique values : 
unique value is :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
for getting the index we should used: 
indexices is:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
counts the repeated values: 
occurence_count 
 [3 4 2 2 2 2 1 1 1 1 1]


For getting the unique row and unique_column we can use the axis for them 

In [41]:
import numpy as n
arr=n.array([[1,2,3,4],[5,9,7,8],[9,1,11,12],[1,2,3,4]])
print("array is\n",arr)
print("for unique row: ")
unique_row=n.unique(arr,axis=0)
print("unique row is: \n",unique_row)
print("for unique column is: ")
print("unique column ")
unique_column=n.unique(arr,axis=1)
print("unique column is:\n ",unique_column)


array is
 [[ 1  2  3  4]
 [ 5  9  7  8]
 [ 9  1 11 12]
 [ 1  2  3  4]]
for unique row: 
unique row is: 
 [[ 1  2  3  4]
 [ 5  9  7  8]
 [ 9  1 11 12]]
for unique column is: 
unique column 
unique column is:
  [[ 1  2  3  4]
 [ 5  9  7  8]
 [ 9  1 11 12]
 [ 1  2  3  4]]


# Transposing and reshaping a matrix
This section is covers the arr.reshape(),arr.transpose(),arr.T
It’s common to need to transpose your matrices. NumPy arrays have the property T that allows you to transpose a matrix.
Transpose: refer to the change the dimension of the matrix as like 2D array is the dimension of (3*2) and after the transposing it becomes the (2*3) 

In [42]:
import numpy as nn
n=nn.array([[1,2,3,4],[6,7,8,9],[0,1,2,3]])
print("arrays is :\n ",n)
print("before transposing the shape is : ",n.shape)
tr=n.reshape(4,3)
print("after transposing is:\n ",tr)
tr1=n.reshape(2,6)
print("with the dimension of 3*3",tr1)

arrays is :
  [[1 2 3 4]
 [6 7 8 9]
 [0 1 2 3]]
before transposing the shape is :  (3, 4)
after transposing is:
  [[1 2 3]
 [4 6 7]
 [8 9 0]
 [1 2 3]]
with the dimension of 3*3 [[1 2 3 4 6 7]
 [8 9 0 1 2 3]]


In [43]:
import numpy as np
ar=np.array([[1,2],[4,5],[3,4]])
print("array is:\n ",ar)
print("shape is: ",ar.shape)
tr=ar.transpose()
#we can also use the ar.T
print("transosing here :\n ",tr)
print("after transpose we get the shape as :\n ",tr.shape)

array is:
  [[1 2]
 [4 5]
 [3 4]]
shape is:  (3, 2)
transosing here :
  [[1 4 3]
 [2 5 4]]
after transpose we get the shape as :
  (2, 3)


**How to reverse the numpy array **
This cover the np.flip() is used to reverse the array . we can also use the reverse slicing in an numpy array

In [48]:
import numpy as a
arr=a.array([1,2,3,5,6,7,8,10])
print("Array is  ",arr)
print("reverse array is: ",arr[::-1])
reverse_array=np.flip(arr)
print("by using the flip function ()",reverse_array)


Array is   [ 1  2  3  5  6  7  8 10]
reverse array is:  [10  8  7  6  5  3  2  1]
by using the flip function () [10  8  7  6  5  3  2  1]


# Work with the 2d Array
do the same work with them also
we can also used to reverse it with row wise(axis=0) and for column wise (axis=1)

In [54]:
import numpy as nn
arr2d=nn.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array is:\n ",arr2d)
rever=nn.flip(arr2d)
print("reverse array is: \n",rever)
rever_row=nn.flip(arr2d,axis=0)
print("for row wise reverse: \n",rever_row)
rever_column=nn.flip(arr2d,axis=1)
print("for column wise: \n",rever_column)

2D array is:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
reverse array is: 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
for row wise reverse: 
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
for column wise: 
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [60]:
import numpy as nnp
arr2d=nnp.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array 2d is: \n",arr2d)
arr2d[0]=nnp.flip(arr2d[0])
print("With the 0 index value reverse: ",arr2d)
arr2d[1]=nnp.flip(arr2d[1])
print("with the 1  index value reverse: \n ",arr2d)
arr2d[2]=nnp.flip(arr2d[2])
print("with the 2 index  value reverse: \n",arr2d[2])

Array 2d is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
With the 0 index value reverse:  [[3 2 1]
 [4 5 6]
 [7 8 9]]
with the 1  index value reverse: 
  [[3 2 1]
 [6 5 4]
 [7 8 9]]
with the 2 index  value reverse: 
 [9 8 7]


You can also reverse the column at index position (the second column)


In [62]:
import numpy as nnp
arr2d=nnp.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array 2d is: \n",arr2d)
arr2d[:,1]=nnp.flip(arr2d[:,1])
print("With the 0 index  column value reverse: ",arr2d)

Array 2d is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
With the 0 index  column value reverse:  [[1 8 3]
 [4 5 6]
 [7 2 9]]


# We can understand the reshaping and flattening  multidimensional array. 
There are two popular ways to flatten an array: .flatten() and .ravel(). The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.
flatten() affect the updated array not the parent array

In [72]:
import numpy as yy
x=yy.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
print("2d array is \n",x)
print("we can done to change the 2d array into 1d array",x.flatten())
a1=x.flatten()
a1[0]=100
print("our parent array is : \n",x)
print("upldated array is\n",a1)
rav=x.ravel()
rav[0]=99
print("our parent array :\n",x)
print("our updated array is: \n",rav)

2d array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]
we can done to change the 2d array into 1d array [ 1  2  3  4  5  6  7  8 11 12 13 14]
our parent array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]
upldated array is
 [100   2   3   4   5   6   7   8  11  12  13  14]
our parent array :
 [[99  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]
our updated array is: 
 [99  2  3  4  5  6  7  8 11 12 13 14]


# How to save and load NumPy objects
This section covers np.save, np.savez, np.savetxt, np.load, np.loadtxt
for saving we can use the **np.save("filename",array)**
for loading the file name with we can also used the **np.load("filename.npy")**
NumPy array as a plain text  file like **.csv or .txt** file use **np.savetxt()**
The savetxt() and loadtxt() functions accept additional optional parameters such as header, footer, and delimiter. While text files can be easier for sharing, .npy and .npz files are smaller and faster to read. If you need more sophisticated handling of your text file (for example, if you need to work with lines that contain missing values), you will want to use the genfromtxt function.

With savetxt, you can specify headers, footers, comments, and more.

In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
np.save("hel",a)
data=np.load('hel.npy')
print(data)
csv_data=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
csv=csv_data.astype(int)
c_data=np.savetxt("numpy_csv.csv",csv_data)
print(csv)
c=np.loadtxt("numpy_csv.csv")
print(c)


[1 2 3 4 5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [43]:
import numpy as np
x=np.array([1,2,3,4,6,7,8,9])
file_name=np.save("helnlo",x)
print(file_name)
data=np.savetxt("second.csv",x,delimiter=",")
b=x.tofile('foo.csv',sep=".",format="%10.0f")
bb=np.array([[1,2,3],[4,5,6],[7,8,6]])
print(bb)
c=bb.tofile("hell.csv",format="%10.0f",sep=',')
print(b)

None
[[1 2 3]
 [4 5 6]
 [7 8 6]]
None


In [50]:
import numpy  as nm
narr=nm.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(narr)
cs=np.savetxt("values.csv",narr,fmt="%d")
print(cs)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
None
