# PANDAS : Pandas is a python package that provides facts,flexible and expensive data structure designed to make working with 'relationals' or 'labelled' data both easy and intutive .
It aims to be the fundamental high-level building block for doing practical ,Real world data analysis in Python

DataFrame and series are quite similarly in that many you can do with other,such as filling in null values and calculating the mean.
The two primary component of the pandas are: 
1: Series  A series is essentially a column  
2: DataFrame: A dataFrame is a multi dimentional table made up of the series.

Lets take the example formation of Dataset :
There are the different ways to create the dataset .
1:by the dictionary
2:By the list
3:Numpy array
Below three one are their example

In [1]:
import pandas as pd
data={
    'apple':[2,1,3,4],
    'orrange':[3,2,3,6]
}
purchase=pd.DataFrame(data)
print(purchase)

   apple  orrange
0      2        3
1      1        2
2      3        3
3      4        6


In [2]:
import pandas as pf
p_list=[['adarsh',21,198,'A'],['ravi','20',165,"B"],['kanishk',22,197,'A']]
data=pf.DataFrame(p_list)
data_1=pf.DataFrame(p_list,columns=['name','age','height','grade'])
print("using list\n",data,"\nusing column list\n",data_1)

#we  can also assign the columns as like


using list
          0   1    2  3
0   adarsh  21  198  A
1     ravi  20  165  B
2  kanishk  22  197  A 
using column list
       name age  height grade
0   adarsh  21     198     A
1     ravi  20     165     B
2  kanishk  22     197     A


In [3]:
#using mpy array
import numpy as np
import pandas as pd
import random 
arr=np.random.randint(1,10,size=(4,3))
print("matrix is:\n ",arr)
df=pd.DataFrame(arr,columns=['col0','col1','col2'])
print(df)

matrix is:
  [[1 4 1]
 [5 3 2]
 [8 7 5]
 [2 6 4]]
   col0  col1  col2
0     1     4     1
1     5     3     2
2     8     7     5
3     2     6     4


At the above three we notice that index is same in all so we also have one value as index=['I0','I1','I3']
lets done one example of it

In [4]:
import pandas as pf
fruits={
    'apple':[2,3,5,7],
    'mango':[3,4,5,9],
    'orange':[2,5,7,9],
    'pineapple':[1,5,7,8],
    'banana':[4,5,7,9],
}
df=pf.DataFrame(fruits,index=['fruit0','fruit1','fruit2','fruit3'])
print("our table is: \n",df)

our table is: 
         apple  mango  orange  pineapple  banana
fruit0      2      3       2          1       4
fruit1      3      4       5          5       5
fruit2      5      5       7          7       7
fruit3      7      9       9          8       9


**Loc()** : This function belongs to work when you  wanted to get the data of small index wise it means for the two or three rows


In [5]:
import pandas as pr
fruit={
    'mango':[2,6,8,5],
    'banana':[4,5,7,4],
}
data_set=pr.DataFrame(fruit,index=['one','two','three','four'])
print(data_set)
#using of loc method
print()
loc=data_set.loc['one']
print(loc)
print()
loc1=data_set.loc['three']
print(loc1)

       mango  banana
one        2       4
two        6       5
three      8       7
four       5       4

mango     2
banana    4
Name: one, dtype: int64

mango     8
banana    7
Name: three, dtype: int64


# example for practises

In [6]:
import pandas as pd
dict={
    'yes':[50,21],
    'no':[131,2]
}
ps=pd.DataFrame(dict)
ps

yes   no
0   50  131
1   21    2

In [7]:
import pandas as pf
dict1={
    'bob':["i like it",'it was awful'],
    'sue':["pretty good","bland!"]
}
data=pf.DataFrame(dict1,index=['product 1',"product 2"])
data


bob          sue
product 1     i like it  pretty good
product 2  it was awful       bland!

# How to read in data:With CSV files all you need is a single line to load in the data:

In [8]:
import pandas as pd
#df=pd.read_csv('languages.csv',encoding="unicode_escape")
#df
dl=pd.read_csv("csv/languages.csv",encoding="unicode_escape")


In pandas there two functions for giving result of the starting row and lasting row
head():This is used to print the five rows of your dataframe as well **df.head()** or we can also use the **df.head(10)** for this no we can print the no of rows
Tail(): It give the last five row and also accept thebno in case of printed last rows **df.tail()** and **df.tail(10)** it printed the 10 rows from the bottom

In [9]:
import pandas as p
languages=p.read_csv("csv/languages.csv")
#languages.head(7)
languages.tail(10)

name  year  quarter  count
3452   Ruby  2022        1    483
3453    PHP  2022        1    445
3454    C++  2022        1    349
3455    Nix  2022        1    279
3456     Go  2022        1    206
3457     C#  2022        1    187
3458      C  2022        1    152
3459   HTML  2022        1    134
3460  Scala  2022        1    110
3461  Shell  2022        1    103

**info() :This is used to know how much dataset use its memory .And all the basically information of the data.**

In [10]:
languages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3462 entries, 0 to 3461
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     3462 non-null   object
 1   year     3462 non-null   int64 
 2   quarter  3462 non-null   int64 
 3   count    3462 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 108.3+ KB


In [11]:
languages.shape

(3462, 4)

**Handling dublicate: Many of the datasets having the duplicates data or dupicate rows,but it is very important to verify the aggregated data**This bring to dupicate the data and just increase your data 2 times


In [12]:
temp=languages.append(languages)
temp.shape

C:\Users\HP\AppData\Local\Temp/ipykernel_9136/2582466552.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  temp=languages.append(languages)


(6924, 4)

To check the dublication we should use the # ```python
drop_duplicate()
```
using the **inplace=True** for modify the DataFrame which is used with keep Arguement  working as keep=First,keep=last,Keep=False
where first is drop duplicates with  the first occurence,last is duplicates except last occurence,False is drop all duplicates


In [13]:
temp_language=languages.drop_duplicates(inplace=True)
temp_language

In [14]:
temp_lang=languages.append(languages)
temp_lang.drop_duplicates(inplace=True,keep=False)
temp_lang.shape

C:\Users\HP\AppData\Local\Temp/ipykernel_9136/2993246692.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  temp_lang=languages.append(languages)


(0, 4)

# column cleaning 
column cleaning is work with the renaming process in which we can use to rename the column by using the .rename() in which we can get the renaming process using dictionary .

In [18]:
import pandas 
dff=pandas.read_csv("csv/languages.csv")
dff.columns

Index(['name', 'year', 'quarter', 'count'], dtype='object')

In [24]:
dff.rename(columns={
    'year':'YEAR',
    "quarter":"QUARTER"
},inplace=True)
dff.columns

Index(['name', 'YEAR', 'QUARTER', 'count'], dtype='object')

In [25]:
dff.columns=[col.lower() for col in dff]
dff.columns

Index(['name', 'year', 'quarter', 'count'], dtype='object')

# Deal with the missing values
while working with the data sometimes we have the problem dealing with empty data or null data .Most commonly you w'll se with **python nonetype** and **numpy np.nan** 
There are two options in dealing with nulls
a) Get rid of rows or columns with nulls
b) Replace nulls with non-null values, a technique known as imputation
first we have to know which cell is null in our dataset


In [4]:
import pandas as pn
data=pn.read_csv("csv/languages.csv")
data.isnull().sum()

name       0
year       0
quarter    0
count      0
dtype: int64

In [41]:
import pandas as pd
dd=pd.read_csv("csv/issues.csv")
revenge=dd['year']
r_m=revenge.mean()
tt=revenge.fillna(r_m,inplace=True)
dd.isnull().sum()
#revenge.median()
#dd['name'].value_counts().head(10)

name       0
year       0
quarter    0
count      0
dtype: int64

In [46]:
dd['name'].describe()


count           3375
unique           178
top       JavaScript
freq              43
Name: name, dtype: object

In [47]:
dd['name'].value_counts().head(10)

JavaScript    43
Python        43
PHP           43
Java          43
C++           43
C             43
C#            43
Ruby          42
TypeScript    41
Erlang        41
Name: name, dtype: int64